- CMakeLists.txt
- script/flucoma-buildtype.cmake
This is the new build type for testing. It uses the CMake built-in `RelWithDebInfo` as its basis, but removes the `NDEBUG` flag so that we still have assertions. This means that on Mac / Linux we have something like `-O2 -g`, i.e. some optimization and debug info, plus assertions. 
Before merging we just need to agree on the name. Currently it's called `Test`, and you'd select it like any other build type. E.g., if using make or ninja as your generator
```bash
cmake <stuff> -DCMAKE_BUILD_TYPE=Test
```
If you'd rather it were called something else, now is the time to say. 
Before it can be used, I need to add a line to each of the host top level CMakeLists to include the type, but it seems to work just fine.
> Add new built type based on RelWithDebInfo plus asserts

- include/clients/common/BufferAdaptor.hpp
Clearly people are making heavy use of our frame and channel offsets 😆 
We seem to have made it this far without me factoring these into the range checking used in the NRT wrapper and elsewhere, as just discovered by @g-roma
> Include offsets in buffer range checks for actual checkingness

- include/clients/common/MemoryBufferAdaptor.hpp
Make the assignment of buffer data in threaded jobs more robust if the buffer is invalid / not there
> Increase safety of assignment with stronger checking before read

- include/algorithms/public/EnvelopeGate.hpp
resolves #22 
Checked in SC and Max. SC tests pass. 
In the interests of simplicity in already complex code, the current implementation updates its input and output buffers by block copying the old buffer content to its new positions. This introduces a great deal of overhead, which grows markedly as `minLengthAbove` / `minLengthBelow` get bigger, and pegs out at 100% CPU for reasonable-seeming values. 
Rather than copying the data around, here I instead do the conventional ring buffer thing of moving read / write heads through the buffers. The downside, obviously, is that operations that were previously on contiguous ranges now sometimes have to be split into two operations, where the range crosses the edges of the buffer. This adds complexity / decreases clarity. On the upside, it means …
> EnvelopeGate: Address performance by avoiding (so much) copying

- include/clients/rt/MFCCClient.hpp
Adds a new param to MFCC to drop the 0th coefficient. Will automatically show up in Max, and if we like it we can add to the SC class.
> Add option to drop 0th MFCC

- include/clients/nrt/FluidSharedInstanceAdaptor.hpp
A slightly embarrassing bug for shared objects that caused crashes when named-shared objects (only named-shared objects were being deleted). Unlikely to be seen often in SC, but could have caused the odd crash in Max with `dataset~/labelset~` when reinstantiating boxes. Due to there now being many more named-shared types on my branch-in-progress, I ran into this during testing. 
For future ref, one needs to remember (d'oh) that `std::remove_if` always needs to be used in conjunction with an actual `erase` operation on the container in question: `remove` only shuffles things about, it doesn't actually do the erasure. If you forget this, then one's container still has dead things littering it.
> Fix crash due to incorrect removal of dead param listeners for shared objects

- include/clients/rt/MFCCClient.hpp
fixes #59 
Problem was that after `reset` the DCT object has wrong size (gives a handy assertion death in debug(
> MFCCs: Ensure DCT reinits to correct size on `reset`

- CMakeLists.txt
fix #53 
Updates tag for HISSTools, hopefully allowing M1 builds out of the box.
> Update CMake to use HISSTools incorporating M1 compatibility

- CMakeLists.txt
Fix #51  – repo for Eigen should be at Gitlab, not Github mirror that is no longer maintained
> Update Eigen repository in CMake FetchContent to Gitlab

- CMakeLists.txt
Caused more trouble than it solved, especially for mac UB2. 
Passing `FLUID_ARCH` from the command line should still work. This just gets rid of the hidden magic that would try and set `march` and `mtune`. If we start using CMake presets, then that would offer a less hideous way to share some useful options in a less brittle way, maybe.
> Remove SIMD detection magic from CMake

- include/clients/nrt/MLPClassifierClient.hpp
Pretty simple, but lead to hilarious crashes when the batch was negative.
> MLP: batchsize was not capped down

- script/flucoma_version.cmake
This uses `git log` to retrieve abbreviated SHAs for flucoma-core and the project being built, and appends them to the version string. 
I've used the [semantic versioning guidelines for including build meta data](https://semver.org/#spec-item-10)
>Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85, 1.0.0+21AF26D3—-117B344092BD.
> Add local + core commit SHAs to version string

- CMakeLists.txt
This disables BLAS for eigen in the builds for APPLE.
In the future it should be revisited, especially with 3.4 Eigen which might solve the problem.﻿
> Toggle BLAS settings for compiling on APPLE

- include/clients/rt/NoveltySliceClient.hpp
This PR adds chroma to NoveltySlice. The new enum is "Spectrum", "MFCC", "Chroma", "Pitch", "Loudness", so code using pitch or loudness would be affected. Tested in SC. The SC class does not need modification, but the helpfiles on all platforms would need to be updated.
For using with tonal material larger kernel sizes than the default (3) are advised.
> add chroma feature to NoveltySlice

- include/clients/rt/ChromaClient.hpp
- include/clients/rt/MFCCClient.hpp
- include/clients/rt/MelBandsClient.hpp
This test code should show the difference.
```
x = {|nband=10| FluidChroma.kr(WhiteNoise.ar(0.2), nband, normalize: 1, maxNumChroma: 12).poll(1)}.play
//10 wiggles
x.set(\nband, 4)
//sample and hold instead of 0 for bands 5-10 (now fixed)
// ====
x = {|nband=10| FluidMelBands.kr(WhiteNoise.ar(0.2),nband,maxNumBands: 10).poll(1)}.play
//10 wiggles
x.set(\nband, 4)
//sample and hold instead of 0 for bands 5-10
// ====
x = {|nband=10| FluidMFCC.kr(WhiteNoise.ar(0.2),nband,maxNumCoeffs: 13).poll(1)}.play
//10 wiggles
x.set(\nband, 4)
//sample and hold instead of 0 for bands 5-10
s.reboot
```
> fix issue #23 - zeroing the output vector in the mTracker loop

- include/clients/rt/NoveltySliceClient.hpp
closes #86 
This is a trivial change, fixing what seems to be a typo in the `NoveltySliceClient`. However, existing example code and stuff you might all be working on that uses novelty slicing with MFCCs will possibly be affected and need re-tuning. Hence a PR rather than just changing it. 
The expected results on the test will certainly need to change.
> Amend upper frequency limit of mel bands in NoveltySlice to 20kHz

- tests/CMakeLists.txt
- tests/clients/common/TestBufferedProcess.cpp
- tests/clients/common/TestFluidSink.cpp
- tests/clients/common/TestFluidSource.cpp
This adds tests for the input framing and overlap-add in `clients/common` 
If one of you could verify that it works for you and then merge, that'd be ace (because I've got another one to come straight away!)
To test that it works configure and build with `FLUCOMA_TESTS` enabled, and from the build folder run `ctest .`
> Tests for framing and overlap add bits

- include/clients/common/FluidNRTClientWrapper.hpp
- include/clients/rt/AudioTransportClient.hpp
Because this affects (at least) 3 of our repos, I thought it would be good to get everyone's eyes over it!
This converts BufAudioTransport's arguments to an A/B based system for the two input buffers. I tested this and it all seems to be working great.
In response to: https://github.com/flucoma/flucoma-docs/issues/66
Parallel to:
* https://github.com/flucoma/flucoma-sc/pull/62
* https://github.com/flucoma/flucoma-docs/pull/69
> BufAudioTransport now has A-B based arguments

- CMakeLists.txt
- README.md
> bump Eigen version

- include/data/FluidTensor_Support.hpp
- tests/data/TestFluidTensorSupport.cpp
A small fix to how `SliceIterator` calculates its `end()`: in certain circumstances slices with size 0 could miscalculate, leading to surprising behaviour with stl algorithms.
> `SliceIterator::end()` fix

- FlucomaVersion.cmake
This bumps the version of the toolkit to beta5 which will be followed by a merge of dev -> main.﻿
> [Version] Bump version of core to beta5

- include/clients/common/ParameterSet.hpp
- include/clients/nrt/BufStatsClient.hpp
- include/clients/nrt/FluidSharedInstanceAdaptor.hpp
- include/data/FluidMeta.hpp
Small additions to parameter set that improve applying functions to subsets of parameters by type, and for finding out how many parameters of a given type there are. 
This is in support of POC work for buffer processing objects being able to supply default output buffers, and to make lower-boilerplate chaining of processes easier (initially in Max, but might be applicable to other hosts)
> Enhance `ParameterSet`

- include/clients/nrt/CommonResults.hpp
- include/clients/nrt/DataSetClient.hpp
- include/clients/nrt/LabelSetClient.hpp
In two cases the use of the word label is out of date with how we currently teach the toolkit. This has been replaced with identifier in the appropriate error message. Similarly `id` should be replaced with identifier as to not confuse native speakers.
> [Fix] Make error language more consistent

- include/clients/common/ParameterSet.hpp
- include/clients/common/TupleUtilities.hpp
Apropos #99, @g-roma wanted a facility to insert a parameter declaration into an existing set
e.g.
```c++ 
constexpr auto SKMeansParams = insertParameterAfter<1>(
KMeansParams,
FloatParam("encodingThreshold", "Encoding Threshold", 0.25, Min(0), Max(1))
); 
```
to save writing
```c++
constexpr auto SKMeansParams = defineParameters(
StringParam<Fixed<true>>("name", "Name"),
LongParam("numClusters", "Number of Clusters", 4, Min(0)),
FloatParam("encodingThreshold", "Encoding Threshold", 0.25, Min(0), Max(1)),
LongParam("maxIter", "Max number of Iterations", 100, Min(1)));
```
> ParameterDescriptors: make more composable by adding insert function

- include/algorithms/public/NoveltySegmentation.hpp
- include/clients/rt/NoveltySliceClient.hpp
fixes #128 by properly resetting the client's frame offset counter when the window / hop size change. Also zero the internal peak buffer for good measure.
> `NoveltySlice`: Fix reset after parameter change (issue #128)

- include/clients/common/FluidNRTClientWrapper.hpp
- include/clients/rt/LoudnessClient.hpp
- include/clients/rt/PitchClient.hpp
- include/clients/rt/SpectralShapeClient.hpp
In keeping with the consistency of SpectralShape and BufStats, I think that Loudness should also include a ChoicesParam. This implements it in what I thought was the most similar way to SpectralShape and which is stylistically pretty much the same.
> [Enhance] ChoicesParam for LoudnessClient and PitchClient

- include/algorithms/public/Normalization.hpp
- include/algorithms/public/RobustScaling.hpp
- include/algorithms/public/Standardization.hpp
- include/algorithms/util/ScalerUtils.hpp
As discovered by Rodrigo, when ranges are near zero, the algorythm gets unstable. In line with ScikitLearn, this is a proposed sanitizer of all ranges that might become denominators in scaling.
> dealing with scaler range near 0

- include/clients/rt/NMFMorphClient.hpp
Changes the parameter `interp` to `interpolation` for the NMFMorph client.
This normalises it to be the same as other objects which have a similarly named parameter.
Relevant PRs:
https://github.com/flucoma/flucoma-sc/pull/115
https://github.com/flucoma/flucoma-core/pull/174
https://github.com/flucoma/flucoma-docs/pull/143
> [Enhance] Interp to Interpolation in NMFMorph

- include/clients/rt/MFCCClient.hpp
This fixes the bug found by @tedmoore - startCoeff wasn't working and now it works.
> MFCC - fixes startCoeff

- include/clients/common/ParameterConstraints.hpp
- include/clients/common/ParameterSet.hpp
- include/clients/nrt/FluidSharedInstanceAdaptor.hpp
Ths is to guarantee that maxima are correct, and strictly >= their params at all times, esp. in client constructors
> Add functions for applying constraints to param maxima

- .github/workflows/flucoma-core-ci.yml
First change for switching over to doing our business mainly on `main`. This will trigger the core CI tests just on pushes and PRs to main (on the assumption that `dev` will go)
> Make `main` great again

- include/clients/nrt/KDTreeClient.hpp
In this first version, I fixed when (k * pointsize) > outbuf.numFrames - now it fills up to the size of the outbuffer. 
We discussed outputing the size of the number of valid points, thus opening the door to using the radius in RT (always up to the size of the outbuffer) but I have questions on the code.
We can also merge this and keep the options for later.
> better behaving real time query of KDTree

- include/algorithms/public/DataSetQuery.hpp
- include/algorithms/public/KNNClassifier.hpp
- include/clients/nrt/DataSetClient.hpp
- include/data/FluidDataSet.hpp
- include/data/TensorTypes.hpp
fixes #225
Introduces  `Input<X><Y>View>` aliases into TensorTypes.hpp for easier expression of const views
> FluidDataSet: Remove  mutable, deal with fallout

- include/algorithms/public/UMAP.hpp
`UMAP::mEmbedding` had been marked `mutable` in order to avoid some code duplication. `mutable` shouldn't be used in the absence of an accompanying lock if the principle of least astonishment is to be honoured in a multi-threaded situation. 
The problem for the original author was that a long and complex function `optimizeLayout` needs to be called both in mutating and non-mutating circumstances, and buried within nested loops is an optional update of this variable. In order for the function to be callable in a `const` case, it needed to be marked `const`, but also needed to be able to update `mEmbedding` during training. It's certainly an amount / complexity of code that one doesn't want to duplicate. 
Without more involved refactoring, I think the best we can do here is to:
* hoist the …
> UMAP: Remove `mutable`

- include/algorithms/public/DCT.hpp
This PR is the one remaining change from #172 that was not effectively integrated.
I will need to find a patch that demonstrates the speed issue to see if this is a worthwhile optimisation, but it also needs checking for anything that uses DCT. The behaviour to check is that around anything that causes an object to have init() called (so does the object produce the correct results on a second analysis for example)
> Avoid re-making the DCT table if it is already correct when initialising

- examples/README.md
@AlexHarker 
the instruction to avoid #233 and compile examples to find the dependencies properly
guidance to compile examples with local versions of dependencies using the `cmake` cache file path for development is quite vague, perhaps an example initial cache file might be useful ?
> compiling examples readme guide

- include/clients/rt/AmpGateClient.hpp
This seems to fix the filter having memories between calls. @weefuzzy I just have 2 very quick questions for you:
- is the NRT adaptor running init on all those automagically converted? I don't know where to look so any pointers welcome.
- is the way I do it in this PR for that object which has its own magic adaptor the right way?
Thanks for your help
> fixes non-initialisation for NRT version of AmpGate.

- include/algorithms/public/Envelope.hpp
- include/algorithms/public/EnvelopeGate.hpp
check the input to env and envgate and stores the last valid value to replace non-finite values with
> fixes #256 - checking input to env with filters

- include/algorithms/public/Normalization.hpp
- include/clients/nrt/NormalizeClient.hpp
we forgot to compute the mRange in the json reloading... so now it is fixed :)
> fixing fluid.normalize json reloading issue

- include/algorithms/public/EnvelopeSegmentation.hpp
- include/algorithms/public/NoveltySegmentation.hpp
- include/algorithms/public/OnsetSegmentation.hpp
Fixes #259 by setting the init of the debounce counter in the 3 slicers that had it to 0 instead of 1. when 1, the condition when the (infinite state of 0 input) to (any signal) which should correctly trigger an attack at frame 0 was ignored, which is a conceptual error compare to our RT one.
Conceptually, we always assumed silence padding as it is what happens in the CCE in RT to these inputs. It is the less worse option. that counter was starting at 1 and dismissing signal at input.
see the bug report to have a comparison patch. or just approve :)
thanks
> fix #259 init debounce counter

- CMakeLists.txt
- examples/CMakeLists.txt
- examples/describe.cpp
- include/algorithms/util/FFT.hpp
- tests/test_signals/CMakeLists.txt
- tests/test_signals/Signals.cpp.in
This is a PR that updates code and CMake files to deal with HISSTools_Library in header only format, which will be the future of the library.
The changes in the repo have been tested for compilation, but it would be advisable to run some audio tests for sanity in the SC repo and also do some audio testing. In terms of impact on the flucoma ecosystem this pulls in the header-only version of the FFT, which is edited from the previous version - there is no specific reason to expect any issue, but any obvious error is likely to turn up in basic audio testing pretty easily.
> Update flucoma-core for hisstools header-only

- docs/requirements.txt
When building docs, I made a virtual environment and `pip install -r docs/requirements.txt`.
Got errors building because module 'schema' was not found. Here I've added it to requirements.txt
> Add missing python dependencies to requirements.txt

- include/clients/nrt/UMAPClient.hpp
The tree-making seems to need to remove the front of the matrix - there is a boolean in the algo, but since tree making can be run on a square matrix elsewhere in the codebase, this was creating an overflow in UMAP as the client was not checking for a smaller number of neighbour than the number of points.
@weefuzzy and @g-roma if the rejection of the first item at UMAP.hpp:373 in fluid::algorithm::UMAP::makeGraph is right for the algo (I am not certain) then this fixes everything.
> Tree making overrun in UMAP - fixes #277 and #278

- include/clients/nrt/NMFCrossClient.hpp
Hello both
i don't know why the client asks for Odd() but it does. With a default value of 10 in there, there was a little complaining and it was pushed to 11. Is the Odd() request wrong, or was the default wrong? I actionned a fix assuming the latter, but happy to discuss.
> NMFCross: fix polyphony's default value not being odd as requested

- include/algorithms/util/FFT.hpp
What is the road to where paved with? 
This hopefully fixes #258 
`FFT` had been altered some time ago to use a global `setup` object in order to cut down on these expensive things being redundantly created all over the place (quite possibly on the heap? Can't remember...). Instead an assumed hard limit of 2^16 Became A Thing. Unfortunately, nobody (i.e. me) told the rest of the codebase, which happily assumed that anything was possible. Moreover, (a) `FFT::resize()` is assumed by calling code not to fail (!?) and (b) its `assert` was useless because `FFT` was still cheerfully accepting fft sizes > 2^16, even if its `setup` object could never honour that. 
(Seems like now would be a good time to have more unit tests) 
So. I still like the idea of 'normal' FFT usage not spraying lots of …
> fix max fft size fiasco

- include/clients/nrt/KNNClassifierClient.hpp
- include/clients/nrt/KNNRegressorClient.hpp
Motivating incident was discovering that with an 'empty' `KNNClassifier` we can generate JSON that will then cause a crash on read (#274)
First commit here 'fixes' that by identifying such JSON as invalid and error-ing out instead (`KNNClassifier` JSON is combination of `KDTree` and `Dataset` but only the top level was being checked. Now we check the sub-objects by delegating to their JSON validation fns) 
Now we need to check the other serializable objects too.
> Crashes with JSON generated by empty objects

- include/algorithms/util/TruePeak.hpp
fixes #283
Introduce a min upsampling factor to ensure that maximum delay can be anticipated at construction time (would be better, actually, if SR were passed to `TruePeak` at construction time, but one thing at a time).
> TruePeak Interpolator: Ensure enough storage

- include/algorithms/public/TransientExtraction.hpp
- include/algorithms/util/ARModel.hpp
- include/clients/rt/TransientClient.hpp
- include/clients/rt/TransientSliceClient.hpp
Fixes #270 
* Ensure that clients instantiate the transient algorithms with actually sensible max values for order, blocksize, padding
* Add some extra asserts to make future us have an easier time tracing this stuff 
* Properly finish the job for ARModel and ensure that the model order no longer assumed to be the size of the parameters vector 😬
> Fix FluidTransient<Slice> allocations 

- include/flucoma/algorithms/public/MLP.hpp
- include/flucoma/algorithms/public/SGD.hpp
- include/flucoma/clients/nrt/CommonResults.hpp
- include/flucoma/clients/nrt/MLPClassifierClient.hpp
- include/flucoma/clients/nrt/MLPRegressorClient.hpp
- include/flucoma/data/FluidDataSet.hpp
- include/flucoma/data/FluidDataSetSampler.hpp
- include/flucoma/data/FluidTensor.hpp
- include/flucoma/data/SimpleDataSampler.hpp
- include/flucoma/data/detail/DataSampler.hpp
- tests/algorithms/public/TestMLP.cpp
- tests/data/TestFluidDataSet.cpp
fixes #292 
Ok, ok, I know this *looks* like a massive PR, but it's not really 😄 
`SGD::train` assumes that its source and target data are *aligned*, i.e. that each index represents the same ID. This not necessarily the case because we're using unordered containers by design. You can make training silently fail to do anything sensible by adding points to source and target in a different order, for instance. This is baaaaad.
The core of this PR is decoupling the batching and sampling of data from `SGD`, a bit like pytorch. I like that `SGD` doesn't want to know about `DataSet`, it just needed to go further. 
So we have 
* some new classes that do data sampling: a base class, an implementation that properly matches source and target IDs, and a simple implementation for when data really are …
> Ensures source and target IDs are paired up in SGD

- include/flucoma/clients/common/FluidBaseClient.hpp
- include/flucoma/clients/nrt/FluidSharedInstanceAdaptor.hpp
@tremblap discovered that the most recent clang is newly upset by calls like `x.template f()`, i.e. where the template argument list is absent. We had two such, seemed like a resonable thing to complain about really.
> Fix missing template args caught by new clang

- include/flucoma/clients/nrt/DataSetClient.hpp
we should make sure that post-trigger, the past is forgotten.
> correct the initialisation post-trigger of the mLastNumPoints

- include/flucoma/clients/common/SpikesToTimes.hpp
This fix makes the sorting in this part of spikesToTimes much faster, for reasons...
> optimise spikes to times sorting

- include/flucoma/clients/nrt/DataSetClient.hpp
- include/flucoma/clients/nrt/KDTreeClient.hpp
fixes #184 by adding checks both in the parameter description and at the recup of optional arguments
> dataset and kdtree - k nearest is checked for min number of k

- include/flucoma/data/FluidTensor.hpp
FliudTensor converting ctr test failing in weird way
> Fix for windows CI
